spring.datasource.url=jdbc:mysql://[centavus-app-nkalyson2-a57e.e.aivencloud.com:14231/defaultdb?sslMode=REQUIRED](https://centavus-app-nkalyson2-a57e.e.aivencloud.com:14231/defaultdb?sslMode=REQUIRED)
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_WIUnfdERHvnmVsZ6_kf
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect